[tool.uv.workspace]
members = [
    "data",
    "learning",
    "notebooks",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "pre-commit>=4.2.0",
    "pytest>=8.3.5",
    "pytest-cov>=6.0.0",
    "pytest-testmon>=2.1.3",
    "pytest-watcher>=0.4.3",
]

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint.pycodestyle]
max-doc-length = 88